#
# Addresses as need to be used;
#   BASE is the base address for the application, within .exe the offset to the
#   .text section is under normal circumstances 0x1000.
#
BASE_ADDRESS = 0x00800000
TEXT_ADDRESS = 0x00801000

all:
    nasm -f win32 -O0 --prefix _ -DADDRESS=$(TEXT_ADDRESS) va_call.asm
    cl -nologo -c -W3 -EHsc -Zc:wchar_t -O2 -Oy- wmain.cpp
    link -nologo -opt:noref -base:$(BASE_ADDRESS) wmain.obj va_call.obj

test: all
    wmain.exe

clean:
    del *.pdb
    del *.obj
    del *.exe
    del *.ilk
